### ISSUE TITLE
Running example pipeline

### ISSUE THREAD

**Issue by joshua-gould** [feldman4/OpticalPooledScreens#14]
```
(ops) ~/code/OpticalPooledScreens$ python -m ops.paper.cell_idr setup_example example --ascp=ascp
Linked barcodes.csv
Linked config.yaml
Linked Snakefile
Traceback (most recent call last):
  File "/Users/gouldj2/miniconda3/envs/ops/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/gouldj2/miniconda3/envs/ops/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/gouldj2/code/OpticalPooledScreens/ops/paper/cell_idr.py", line 132, in <module>
    fire.Fire(commands)
  File "/Users/gouldj2/miniconda3/envs/ops/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Users/gouldj2/miniconda3/envs/ops/lib/python3.10/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Users/gouldj2/miniconda3/envs/ops/lib/python3.10/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/gouldj2/code/OpticalPooledScreens/ops/paper/cell_idr.py", line 106, in setup_example
    get_cell_idr(directory, well=well, tile=tile, ascp=ascp)
  File "/Users/gouldj2/code/OpticalPooledScreens/ops/paper/cell_idr.py", line 61, in get_cell_idr
    raise ValueError('No valid tiles specified for the chosen experiment.')
ValueError: No valid tiles specified for the chosen experiment.
```

**Comment by lukebfunk** [comment]
Thanks for bringing this up, @joshua-gould. I just fixed a small typo in the example function, please pull updates and try again.

**Comment by joshua-gould** [comment]
Thanks
